# docker: https://qiita.com/minato-naka/items/8b31d28823cabaa9487a
# node:   https://www.hypertextcandy.com/vue-laravel-tutorial-setting-up-spa-project
# php.ini https://qiita.com/A-Kira/items/1c55ef689c0f91420e81

# Docker Composeのバージョン
version: "3"
# 作成するコンテナを定義
services:

  php:
    ## コンテナの名前
    container_name: php
    ## コンテナの元になるDockerfileがおいてあるパス
    build: ./docker/php
    ## ホストPC側のプログラムソースディレクトリをマウント
    volumes:
    - ./server:/var/www

  nginx:
    ## Nginxコンテナのもとになるイメージを指定
    image: nginx
    ## コンテナの名前
    container_name: nginx
    ## ホスト側の80番ポートとコンテナ側の80番ポートをつなげる
    ports:
    - 80:80
    ## ホストPC側をnginxにマウント
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ## 依存関係
    depends_on:
    - php

  db:
    ## イメージを指定
    image: mysql:5.7
    ## これがホスト名になるので env では「DB_HOST=db-host_db」とする
    container_name: db-host
    ## db設定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ## コマンドで設定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ## ホスト側のポートとコンテナ側のポートをつなげる
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ## ホスト側のポートとコンテナ側のポートをつなげる
    ports:
    - 3306:3306

  redis:
    ## イメージを指定
    image: redis:latest
    ## これがホスト名になるので env では「REDIS_HOST=redis-host_db」とする
    container_name: redis-host
    ## ホスト側のポートとコンテナ側のポートをつなげる
    ports:
      - 6379:6379
